<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>GKIN</RootNamespace>
    <AssemblyName>GKIN</AssemblyName>
    <LangVersion>latest</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\bin\</OutputPath>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoCAD.NET" Version="24.3.0" />
  </ItemGroup>
</Project>
