<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>GKIN</RootNamespace>
    <AssemblyName>GKIN</AssemblyName>
    <LangVersion>latest</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\bin\</OutputPath>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <PlatformTarget>x64</PlatformTarget>
    <Version>0.3.7</Version>
    <AssemblyVersion>0.3.7.0</AssemblyVersion>
    <FileVersion>0.3.7.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoCAD.NET" Version="24.0.0" />
    <PackageReference Include="PDFsharp" Version="6.2.0" />
  </ItemGroup>
</Project>
